[package]
name = "konstantynovska_rust"
version = "0.1.0"
edition = "2021"
authors = ["Asya Konstantynovska <nastya.konstantynovska@gmail.com>"]
description = "Мій парсер списків для навчальної практики"
license = "MIT"
readme = "README.md"
repository = "https://github.com/konstanta-asya/crate_rust"
homepage = "https://github.com/konstanta-asya/crate_rust"
documentation = "https://docs.rs/konstantynovska_rust"

[dependencies]
peg = "0.8.5"
