[package]
name = "my_crate_name"
version = "0.1.0"
edition = "2024"
authors = ["Asya Konstantynovska <nastya.konstantynovska@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/konstanta-asya/crate_rust"
[dependencies]

